# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

title: Hongjian's Blog
email: 190303610@qq.com
description: > 
  This is my blog site.Not only can it include my pics of travel and life,
  but also it contain my post. 
baseurl: ""
#url: "zhouhongjian.github.io"
github_username: zhouhongjian

# Build settings
markdown: kramdown


# Custom Variable settings
bs_path: /assets/plugins/bootstrap3/
#custom_include_path: _includes/custom/
#custom_layout_path: _layout/custom/